nelmio_api_doc:
    documentation:
        info:
            title: Publisher API
            description: API for publishing books and more
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
